@API_URL = http://localhost:3000/api

@TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb2dpbl9pZCI6ImFkbWluIiwicm9sZSI6ImFkbWluIiwiY29tcGFueV9vaWQiOiJDLURFTU8iLCJ0aW1lIjoiZnVuY3Rpb24gaG9va3MoKSB7XG4gICAgICAgIHJldHVybiBob29rQ2FsbGJhY2suYXBwbHkobnVsbCwgYXJndW1lbnRzKTtcbiAgICB9MmU4ZmJiMDItMTE0YS00MDgyLWE3MmItZTUyZDM0OTQwZGQyIiwiaWF0IjoxNjg5Mzk4ODM0LCJleHAiOjE2ODk0ODUyMzR9.zNfmVEeWle4aadydlvaX270n287pMofOWD6t4SiXBUE


### Save/Update people
POST {{API_URL}}/v1/people/save-update
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{TOKEN}}

{ 
    "name": "Rohan ", 
    "mobile_no":"0191281770",
    "email": "rohan@gmail.com", 
    "people_type": ["Customer"],  
    "receivable_balance": 500, 
    "status": "Active" 
}



### Get people by oid
POST {{API_URL}}/v1/people/get-by-oid
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{TOKEN}}

{ 
    "oid": "P-001"
}