variables:
    PRODUCT_NAME: 'gds'
    APP_NAME: '04_api'
    NETWORK: 'app_net'

stages:
    - dev

dev-docker:
    stage: dev
    only:
        - dev
    tags:
        - dev
    script:
        - export VERSION=$(date +%Y%m%d_%H%M%S)
        - IMAGE_NAME=${PRODUCT_NAME}_${CI_JOB_STAGE}_${APP_NAME}
        - SERVICE_NAME=${PRODUCT_NAME}_${CI_JOB_STAGE}_${APP_NAME}
        - docker build --tag=${IMAGE_NAME}:${VERSION} --build-arg NODE_ENV=${CI_JOB_STAGE} .
        - S_NAME=$(echo `docker service ls --filter name="${SERVICE_NAME}" --format "{{.Name}}"`)
        - >
            if [ ! -z "${S_NAME}" ]; then
                docker service update --image ${IMAGE_NAME}:${VERSION} ${SERVICE_NAME}
            else
                docker service create --name ${SERVICE_NAME} --replicas 1 --mount type=volume,source=gds_log_data,destination=/app/log --network ${NETWORK} ${IMAGE_NAME}:${VERSION}
            fi
