variables:
    IMAGE_NAME: 'gds-04-api'
    SERVICE_NAME: 'gds_04_api'
    NETWORK: 'app_net'

stages:
    - dev

dev-docker:
    stage: dev
    only:
        - dev
    tags:
        - dev
    script:
        - export VERSION=$(date +%Y%m%d_%H%M%S)
        - docker build --tag=${IMAGE_NAME}-dev:${VERSION} --build-arg NODE_ENV=dev .
        - S_NAME=$(echo `docker service ls --filter name="${SERVICE_NAME}_dev" --format "{{.Name}}"`)
        - >
            if [ ! -z "${S_NAME}" ]; then
                docker service update --image ${IMAGE_NAME}-dev:${VERSION} ${SERVICE_NAME}_dev
            else
                docker service create --name ${SERVICE_NAME}_dev --replicas 1 --mount type=volume,source=gds_log_data,destination=/app/log --network ${NETWORK} ${IMAGE_NAME}-dev:${VERSION}
            fi
