@API_URL = http://localhost:3000/api

@TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb2dpbl9pZCI6ImFkbWluIiwicm9sZSI6ImFkbWluIiwiY29tcGFueV9vaWQiOiJDLURFTU8iLCJ0aW1lIjoiZnVuY3Rpb24gaG9va3MoKSB7XG4gICAgICAgIHJldHVybiBob29rQ2FsbGJhY2suYXBwbHkobnVsbCwgYXJndW1lbnRzKTtcbiAgICB9ZjVkZmMzYjUtYmU4YS00ZTAyLThiNjItZTUwM2Y5YTM3ZjlmIiwiaWF0IjoxNjg3NDk0OTA1LCJleHAiOjE2ODc1ODEzMDV9.aTqQqbEvvpZk8xb4vT0w6z9sLYf2mVMLKEPx9sp9Pjc


### Save/Update product unit
POST {{API_URL}}/v1/inventory/product-category/save-update
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{TOKEN}}

{
    "name":"RRRRR",
    "status":"Active"
}


### Get the list of product unit
POST {{API_URL}}/v1/inventory/product-category/get-list
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{TOKEN}}

{
    "status":"Active",
    "offset":1,
    "limit":10
}