@API_URL = http://localhost:3000/api

@TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb2dpbl9pZCI6ImFkbWluIiwicm9sZSI6ImFkbWluIiwiY29tcGFueV9vaWQiOiJDLURFTU8iLCJ0aW1lIjoiZnVuY3Rpb24gaG9va3MoKSB7XG4gICAgICAgIHJldHVybiBob29rQ2FsbGJhY2suYXBwbHkobnVsbCwgYXJndW1lbnRzKTtcbiAgICB9MzQ1ZjFmZTctOGRkOC00Y2NhLTlmYzctMzU4MTBmYzk5ZTIyIiwiaWF0IjoxNjg4ODEwMzAwLCJleHAiOjE2ODg4OTY3MDB9.yM2Vq1F_BMbpB8oPWilQbds4_PJ_3jpBbbeucdj8B4U


### Save/Update product unit
POST {{API_URL}}/v1/inventory/product/save-update
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{TOKEN}}

{
    "name":"RRRRR",
    "status":"Active"
}


### Get the list of product unit
POST {{API_URL}}/v1/inventory/product/get-list
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{TOKEN}}

{
    "search_text":"",
    "status":"Active",
    "limit":10,
    "filter_array": [
        {
            "filter_by":"product_category_oid",
            "value":["PC-102","PC-101"]
        }
    ]
}


### Get the product by oid
POST {{API_URL}}/v1/inventory/product/get-by-oid
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{TOKEN}}

{
    "oid":"XN7nsK"
}