@API_URL = http://localhost:3000/api

@TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb2dpbl9pZCI6ImFkbWluIiwicm9sZSI6ImFkbWluIiwiY29tcGFueV9vaWQiOiJDLURFTU8iLCJ0aW1lIjoiZnVuY3Rpb24gaG9va3MoKSB7XG4gICAgICAgIHJldHVybiBob29rQ2FsbGJhY2suYXBwbHkobnVsbCwgYXJndW1lbnRzKTtcbiAgICB9Y2Y2YzM2YmEtYTM5NS00NzEyLWJlMGMtYzRhNjk0OTUyNDBlIiwiaWF0IjoxNjg4NDg5MDc2LCJleHAiOjE2ODg1NzU0NzZ9.XBR6uauB-O39ENjXUfJXg1oB1L52PPRyMZbUV3k8aAM


###
POST {{API_URL}}/v1/inventory/warehouse/save-update
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{TOKEN}}

{
    "oid":"RcEuKA",
    "name":"Hamza is Hamza",
    "address":"Svar union, Dhaka",
    "status":"Active"
}


###
POST {{API_URL}}/v1/inventory/warehouse/get-list
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{TOKEN}}

{
    "status": ["Inactive", "Active"]
}


### change the default warehouse by providing oid 
POST {{API_URL}}/v1/inventory/warehouse/change-default
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{TOKEN}}

{
    "oid":"W-101"
}