@API_URL = http://localhost:3000/api

@TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb2dpbl9pZCI6ImFkbWluIiwicm9sZSI6ImFkbWluIiwiY29tcGFueV9vaWQiOiJDLURFTU8iLCJ0aW1lIjoiZnVuY3Rpb24gaG9va3MoKSB7XG4gICAgICAgIHJldHVybiBob29rQ2FsbGJhY2suYXBwbHkobnVsbCwgYXJndW1lbnRzKTtcbiAgICB9OWFlNTkwNmEtNWJmMi00NmU0LTk4NmYtOWVkYjFiZGI5Yjk1IiwiaWF0IjoxNjg4NTUxNDgzLCJleHAiOjE2ODg2Mzc4ODN9.-zP4odiruwllARYh6912au9dzTp7FbbqGlJRY24m6dw


###
POST {{API_URL}}/v1/inventory/warehouse/save-update
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{TOKEN}}

{
    "oid":"RcEuKA",
    "name":"Hamza is Hamza",
    "address":"Svar union, Dhaka",
    "status":"Active"
}


###
POST {{API_URL}}/v1/inventory/warehouse/get-list
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{TOKEN}}

{   
    "status":["Active", "Inactive"]
}


### change the default warehouse by providing oid 
POST {{API_URL}}/v1/inventory/warehouse/change-default
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{TOKEN}}

{
    "oid":"W-101"
}