@API_URL = http://localhost:3000/api
# @API_URL = http://192.168.1.160:3000/api

@TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb2dpbl9pZCI6ImFkbWluIiwicm9sZSI6ImFkbWluIiwiY29tcGFueV9vaWQiOiJDLURFTU8iLCJ0aW1lIjoiZnVuY3Rpb24gaG9va3MoKSB7XG4gICAgICAgIHJldHVybiBob29rQ2FsbGJhY2suYXBwbHkobnVsbCwgYXJndW1lbnRzKTtcbiAgICB9ZTM1M2M1YjctZTFkMi00YmZmLWI2OWMtYjhiNWI3OTFhNDgyIiwiaWF0IjoxNjg4NjUyMDk0LCJleHAiOjE2ODg3Mzg0OTR9.gbM3cxFCL2H5AhjJybksqsq5YyylDMWGIJKjghCu6OM

###
POST {{API_URL}}/v1/accounting/ledger-setting/get-list
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{TOKEN}}

{ 
    "search_text": "",
    "offset": "",
    "limit": ""

}

###
POST {{API_URL}}/v1/accounting/ledger-setting/get-by-oid
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{TOKEN}}

{ 
    "oid": "ls-demo-0504006"

}

###
POST {{API_URL}}/v1/accounting/ledger-setting/save-update
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{TOKEN}}

{ 

    "ledger_key": "rest",
    "ledger_name": "rest-1",
    "ledger_oid": "lg-demo-0504006"

}

###
POST {{API_URL}}/v1/master/bank-account/delete
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{TOKEN}}

{ 
    "oid": "7ff1c6c4-ff6e-4316-8799-cc0afe1e60cf"

}
