@API_URL = http://localhost:3000/api
# @API_URL = http://192.168.1.160:3000/api

@TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb2dpbl9pZCI6ImFkbWluIiwicm9sZSI6ImFkbWluIiwiY29tcGFueV9vaWQiOiJDLURFTU8iLCJ0aW1lIjoiZnVuY3Rpb24gaG9va3MoKSB7XG4gICAgICAgIHJldHVybiBob29rQ2FsbGJhY2suYXBwbHkobnVsbCwgYXJndW1lbnRzKTtcbiAgICB9OWFlNTkwNmEtNWJmMi00NmU0LTk4NmYtOWVkYjFiZGI5Yjk1IiwiaWF0IjoxNjg4NTUxNDgzLCJleHAiOjE2ODg2Mzc4ODN9.-zP4odiruwllARYh6912au9dzTp7FbbqGlJRY24m6dw
###
POST {{API_URL}}/v1/accounting/ledger-subgroup/get-list
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{TOKEN}}

{ 
    "search_text": "",
    "offset": "",
    "limit": "",
    "ledger_group_oid": "lg-demo-05"
}

###
POST {{API_URL}}/v1/accounting/ledger-subgroup/get-by-oid
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{TOKEN}}

{ 
    "oid": "lsg-demo-0501"
}