@API_URL = http://localhost:3000/api
# @API_URL = http://192.168.1.160:3000/api

@TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb2dpbl9pZCI6ImFkbWluIiwicm9sZSI6ImFkbWluIiwiY29tcGFueV9vaWQiOiJDLURFTU8iLCJ0aW1lIjoiZnVuY3Rpb24gaG9va3MoKSB7XG4gICAgICAgIHJldHVybiBob29rQ2FsbGJhY2suYXBwbHkobnVsbCwgYXJndW1lbnRzKTtcbiAgICB9ZGE0YjkxMDMtZTZiMC00MDkyLWFkZWQtZWYwMzg0MzAyZDU4IiwiaWF0IjoxNjkxMzAyNzAwLCJleHAiOjE2OTEzODkxMDB9._ANL4DzuO1D-emwSzf2gmQLWjuY-myjCllRwRsAElps

###
POST {{API_URL}}/v1/accounting/ledger-subgroup/get-list
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{TOKEN}}

{ 
    "search_text": "0",
    "offset": "",
    "limit": "",
    "ledger_group_oid": "lg-demo-05",
    "ledger_subgroup_name": ""
}

###
POST {{API_URL}}/v1/accounting/ledger-subgroup/get-by-oid
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{TOKEN}}

{ 
    "oid": "lsg-demo-0501"
}
###
POST {{API_URL}}/v1/accounting/ledger-subgroup/save-update
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{TOKEN}}

{ 
    
    "ledger_subgroup_name": "Operating 2",
    "ledger_group_oid": "lg-demo-05"
}