@API_URL = http://localhost:3000/api

@TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb2dpbl9pZCI6ImFkbWluIiwicm9sZSI6ImFkbWluIiwiY29tcGFueV9vaWQiOiJDLURFTU8iLCJ0aW1lIjoiZnVuY3Rpb24gaG9va3MoKSB7XG4gICAgICAgIHJldHVybiBob29rQ2FsbGJhY2suYXBwbHkobnVsbCwgYXJndW1lbnRzKTtcbiAgICB9N2JlMTI2ZjYtNTRjZC00NjU0LTg4MzAtOTAzMjE3MjAwNTUwIiwiaWF0IjoxNjg2OTg5MjU3LCJleHAiOjE2ODcwNzU2NTd9.NnuzDeqjMeYYB-PuZh5jpS-o2vROqgyZDniKNhz2KXo

###
POST {{API_URL}}/v1/meta-property/get-by-oid
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{TOKEN}}

{
    "oid": "M002"
}

###
POST {{API_URL}}/v1/airport/get-list
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{TOKEN}}

{
    "search_text": "HGU"
}
###
POST {{API_URL}}/v1/airline/get-list
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{TOKEN}}

{
    "search_text": ""
}
###
POST {{API_URL}}/v1/country/get-list
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{TOKEN}}

{
    "search_text": "El"
}
###
POST {{API_URL}}/v1/bank/get-list
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{TOKEN}}

{
    "search_text": "ab"
}
###
POST {{API_URL}}/v1/division/get-list
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{TOKEN}}

{
    "search_text": ""
}
###
POST {{API_URL}}/v1/district/get-list
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{TOKEN}}

{   
    "division_oid": "DIV_02",
    "search_text": "n"
}
###
POST {{API_URL}}/v1/thana/get-list
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{TOKEN}}

{   
    "district_oid": "Dist-18",
    "search_text": "n"
}
###
POST {{API_URL}}/v1/post-office/get-list
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{TOKEN}}

{   
    "thana_oid": "Thana-149",
    "search_text": ""
}
###
POST {{API_URL}}/v1/department/get-list
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{TOKEN}}

{   
    "search_text": ""
}
###
POST {{API_URL}}/v1/designation/get-list
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{TOKEN}}

{   
    "search_text": "cook"
}
###
POST {{API_URL}}/v1/bank-account/get-list
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{TOKEN}}

{   
    "search_text": ""
}
###
POST {{API_URL}}/v1/people/get-list
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{TOKEN}}

{   
    "search_text": ""
}