@API_URL = http://localhost:3000/api

@TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb2dpbl9pZCI6ImFkbWluIiwicm9sZSI6ImFkbWluIiwiY29tcGFueV9vaWQiOiJDLURFTU8iLCJ0aW1lIjoiZnVuY3Rpb24gaG9va3MoKSB7XG4gICAgICAgIHJldHVybiBob29rQ2FsbGJhY2suYXBwbHkobnVsbCwgYXJndW1lbnRzKTtcbiAgICB9NzU2NGIzOTItMjMxMC00Y2M2LTgzOTktMTIxMTA4OTQ3NzA1IiwiaWF0IjoxNjg2OTgzMDYzLCJleHAiOjE2ODcwNjk0NjN9.MIH6TSEy-ryMBObzmzdQXntkpUgf1TGoytP4ePACJpw


###

###
POST {{API_URL}}/v1/meta-property/get-by-oid
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{TOKEN}}

{
    "oid": "M002"
}

###
POST {{API_URL}}/v1/airport/get-list
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{TOKEN}}

{
    "search_text": "HGU"
}