@API_URL = http://localhost:3000/api

@TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb2dpbl9pZCI6ImFkbWluIiwicm9sZSI6ImFkbWluIiwiY29tcGFueV9vaWQiOiJDLURFTU8iLCJ0aW1lIjoiZnVuY3Rpb24gaG9va3MoKSB7XG4gICAgICAgIHJldHVybiBob29rQ2FsbGJhY2suYXBwbHkobnVsbCwgYXJndW1lbnRzKTtcbiAgICB9NTc5YzFjMzMtYzhjYi00NDM5LWFjMDctYWQ1NTBiN2I4OWZjIiwiaWF0IjoxNjg3MjgyMDUwLCJleHAiOjE2ODczNjg0NTB9.sLtx5YPv4UiVatxcCqyP5EhhXMi8pQAHjzSmvOAbPQk

###
POST {{API_URL}}/v1/master/setting/department/get-list
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{TOKEN}}

{ 
    "search_text": "",
    "offset": "0",
    "limit": "",
    "status": "Active"

}

###
POST {{API_URL}}/v1/master/setting/department/get-by-oid
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{TOKEN}}

{ 
    "oid": "c7dbabfd-2e16-428e-b661-6309dac8fe74"

}

###
POST {{API_URL}}/v1/master/setting/department/save-update
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{TOKEN}}

{ 
    "name": "Supply Chain",
    "status": "Active"
}

###
POST {{API_URL}}/v1/master/setting/department/update
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{TOKEN}}

{ 
    "oid": "c7dbabfd-2e16-428e-b661-6309dac8fe74",
    "name": "Save",
    "sort_order": "8",
    "status": "Active"

}
###
POST {{API_URL}}/v1/master/setting/department/delete
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{TOKEN}}

{ 
    "oid": "0b8d29a6-87a8-43b7-b9de-aef628a55568"

}
