@API_URL = http://localhost:3000/api

@TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb2dpbl9pZCI6ImFkbWluIiwicm9sZSI6ImFkbWluIiwiY29tcGFueV9vaWQiOiJDLURFTU8iLCJ0aW1lIjoiZnVuY3Rpb24gaG9va3MoKSB7XG4gICAgICAgIHJldHVybiBob29rQ2FsbGJhY2suYXBwbHkobnVsbCwgYXJndW1lbnRzKTtcbiAgICB9YTBmM2ZmOGUtNjYyMS00M2I0LWI0MTYtZDQwNTQwNDY1MjBkIiwiaWF0IjoxNjg3Njc3NTc2LCJleHAiOjE2ODc3NjM5NzZ9.SARtI4RcfDyZkZ2EKblTHGhZYlJUsmzFzVRyNFpEsJ8



### Get the list of product unit
POST {{API_URL}}/v1/activity-log/get-list
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{TOKEN}}

{
    "offset":1,
    "limit":10
}