@BASE_API_URL = http://0.0.0.0:3000/api
# @BASE_API_URL = https://dev.gdsflight.com/api

@TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiYWNhcyIsImNsaWVudF9pZCI6ImFjYXMiLCJzY2hlbWEiOiJhY2FzIiwiaWF0IjoxNjY2MDI3Njc2LCJleHAiOjE2NjYxMTQwNzZ9.UzyoaDqVl0BtMsia56pAK7TjyQmAaUhyM8kOqRdbRMQ

###
POST https://dev.gdsflight.com/api/authentication/user/v1/authenticate-user
Content-Type: application/json
Accept: application/json

{
    "user_id": "gtatravel",
    "password": "123456"
}

###
POST https://dev.gdsflight.com/api/v1/sign-in
Content-Type: application/json
Accept: application/json

{
    "user_id": "gtatravel",
    "password": "123456"
}

###
POST https://dev.gdsflight.com/api/authentication/user/v1/authenticate-user
Content-Type: application/json
Accept: application/json

{
    "user_id": "gtatravel",
    "password": "123456"
}

###
GET {{BASE_API_URL}}/sign-out
Accept: application/json
Authorization: Bearer {{TOKEN}}

###
POST {{BASE_API_URL}}/v1/sign-in
Content-Type: application/json
Accept: application/json

{
    "user_id": "gtatravel",
    "password": "123456"
}

###
GET {{BASE_API_URL}}/get-user-info
Accept: application/json
Authorization: Bearer {{TOKEN}}

{}
