@API_URL = http://localhost:3000/api

@TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb2dpbl9pZCI6ImFkbWluIiwicm9sZSI6ImFkbWluIiwiY29tcGFueV9vaWQiOiJDLURFTU8iLCJ0aW1lIjoiZnVuY3Rpb24gaG9va3MoKSB7XG4gICAgICAgIHJldHVybiBob29rQ2FsbGJhY2suYXBwbHkobnVsbCwgYXJndW1lbnRzKTtcbiAgICB9YTc3ZmY5MjQtZWEzZi00YzYwLWExMTktZTg0NzdkY2E5NjdkIiwiaWF0IjoxNjg2OTM0NTY0LCJleHAiOjE2ODY5MzQ1NzR9.lpWrP9KoQxbrJgSxFdWdHwe159D1W1sclgT9fs9US0I

###
POST {{API_URL}}/v1/user/signin
Content-Type: application/json
Accept: application/json

{
    "login_id": "admin",
    "password": "sa"
}


###
GET {{API_URL}}/v1/user/signout
Accept: application/json
Authorization: Bearer {{TOKEN}}


###
GET {{API_URL}}/v1/user/get-user-profile
Accept: application/json
Authorization: Bearer {{TOKEN}}

